Python 3.4:
    script:
    - export PY_EXE=python3.4
    - virtualenv -p python3 env
    - source env/bin/activate
    - pip install -r requirements.txt
    - python manage.py test --noinput
    - coverage run --source=accounts,cases,common,contacts,emails,leads,opportunity,planner  manage.py test --noinput
    - coverage report -m
    except:
    - tags

deploy_live:
  stage: deploy
  environment:
    name: live
  script:
    - sudo /bin/rm -rf /home/dj_crm/dj_crm/; cp -r . /home/dj_crm/dj_crm
    - source /home/dj_crm/env/bin/activate
    - pip install -r /home/dj_crm/dj_crm/requirements.txt
    - python /home/dj_crm/dj_crm/manage.py migrate --noinput
    - sudo /etc/init.d/uwsgi restart
  only:
    - master
  tags:
    - github-crm
