language: python
python:
  - "3.4"

#Django & Database
addons:
  postgresql: "9.4"

sudo: false

env:
  -DJANGO=1.11

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - gem install sass
  - pip install npm
  - npm install less
  - pip install redis

# command to run tests
script:
  - python manage.py test
  - coverage run --source=accounts,common manage.py test accounts common

after_success:
  coveralls
