version: '2.0'

services:
  db:
    image: postgres
    volumes:
      - /home/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "dj_crm"

  web:
    build: .
    image: micropyramid/django-crm:1
    ports:
      - "8001:8000"
    depends_on:
      - db
