version: '3'
services:
  crm-app:
    image: djcrm:1
    container_name: crm-app
    environment:
      - DBNAME=crm
      - DBUSER=crm
      - DBPASSWORD=crm
      - DBHOST=crm-db
      - DBPORT=5432

    depends_on:
      - crm-db
    ports:
      - 8000:8000
    networks:
      - nw

  crm-db:
    image: postgres:latest
    container_name: crm-db
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=crm
    ports:
      - 5432:5432
    volumes:
      - /var/run/postgresql/:/var/run/postgresql
    networks:
      - nw

networks:
  nw: {}
